
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:

title: ELECTRONICS For the Rest of Us!
description: Learning a little more about Coding...

theme: jekyll-theme-time-machine
